# CodeCov Configuration
# https://docs.codecov.io/docs/codecov-yaml

coverage:
  range: 80..100
  round: down
  precision: 2

  status:
    project:
      default:
        target: 90%
        threshold: 2%
        base: auto
    patch:
      default:
        target: 85%
        threshold: 5%

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

ignore:
  - "tests/**/*"
  - "**/*.test.ts"
  - "**/*.test.js"
  - "**/test-*.ts"
  - "**/test-*.js"
  - "**/__tests__/**"
  - "**/fixtures/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/node_modules/**"
  - "**/*.d.ts"
  - "**/coverage/**"
