yarnPath: .yarn/releases/yarn-4.9.4.cjs

# Modern Yarn v4 configuration
nodeLinker: node-modules

# Network settings
httpTimeout: 60000
httpRetry: 3

# Enable mirror and network for better performance
enableMirror: true
enableNetwork: true

# PnP settings (loose mode for better compatibility with node_modules)
pnpMode: loose

# Performance settings
compressionLevel: 9
networkConcurrency: 50
