[package]
name = "ast-helper-core-engine"
version = "0.1.0"
edition = "2021"
authors = ["AST Copilot Helper Team"]
description = "High-performance WASM core engine for vector operations and AST processing"
license = "MIT"
repository = "https://github.com/EvanDodds/ast-copilot-helper"

[lib]
crate-type = ["lib", "cdylib"]

[[bin]]
name = "ast-parser"
path = "src/bin/ast_parser.rs"
required-features = ["full-system"]

[dependencies]
# WASM-specific dependencies
wasm-bindgen = { version = "0.2" }
wasm-bindgen-futures = { version = "0.4" }
js-sys = { version = "0.3" }
serde-wasm-bindgen = { version = "0.6" }
getrandom = { version = "0.2", features = ["js"] }
uuid = { version = "1.10", features = ["v4", "serde", "js"], default-features = false }

# Async runtime - features depend on target
tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread", "sync", "time", "fs"], default-features = false }

# CLI parsing for binary
clap = { version = "4.5", features = ["derive"], optional = true }
serde_yaml = { version = "0.9", optional = true }

# Database and storage (WASM-compatible)
sqlx = { version = "0.8", features = ["sqlite", "chrono", "uuid", "runtime-tokio"], default-features = false, optional = true }

# Concurrent data structures and sync
dashmap = "6.1"

# System utilities (WASM-compatible)
sysinfo = { version = "0.32", optional = true }
num_cpus = { version = "1.16", optional = true }

# Platform-specific dependencies
libc = { version = "0.2", optional = true }

# AST parsing
tree-sitter = { version = "0.25", optional = true }

# Tree-sitter language parsers - updated to latest versions
tree-sitter-javascript = { version = "0.25.0", optional = true }
tree-sitter-python = { version = "0.25.0", optional = true }
tree-sitter-typescript = { version = "0.23.2", optional = true }
tree-sitter-c = { version = "0.24.1", optional = true }
tree-sitter-java = { version = "0.23.5", optional = true }
tree-sitter-cpp = { version = "0.23.4", optional = true }
tree-sitter-c-sharp = { version = "0.23.1", optional = true }
tree-sitter-rust = { version = "0.24.0", optional = true }
tree-sitter-go = { version = "0.25.0", optional = true }

# Additional language parsers - updated to latest versions
tree-sitter-ruby = { version = "0.23.1", optional = true }
tree-sitter-php = { version = "0.24.2", optional = true }
tree-sitter-kotlin = { version = "1.1.0", optional = true, package = "tree-sitter-kotlin-ng" }
tree-sitter-swift = { version = "0.7.1", optional = true }
tree-sitter-scala = { version = "0.24.0", optional = true }
tree-sitter-bash = { version = "0.25.0", optional = true }
# tree-sitter-dart = { version = "0.0.4", optional = true } # Uses older tree-sitter API

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Futures
futures = "0.3"

# Random utilities
fastrand = "2.0"

# CLI dependencies removed - already defined above

[dev-dependencies]
wasm-bindgen-test = "0.3"
tokio = { version = "1.0", features = ["full"] }
tempfile = "3.0"

[features]
default = ["full-system"]
wasm = [] # WASM build without system dependencies
full-system = ["tree-sitter", "tree-sitter-javascript", "tree-sitter-python", "tree-sitter-typescript", "tree-sitter-c", "tree-sitter-java", "tree-sitter-cpp", "tree-sitter-c-sharp", "tree-sitter-rust", "tree-sitter-go", "tree-sitter-ruby", "tree-sitter-php", "tree-sitter-kotlin", "tree-sitter-swift", "tree-sitter-scala", "tree-sitter-bash", "sqlx", "sysinfo", "num_cpus", "libc", "clap", "serde_yaml"] # Include system dependencies for native builds

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.release-with-debug]
inherits = "release"
debug = true
strip = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O", "--enable-bulk-memory", "--enable-nontrapping-float-to-int"]