[package]
name = "ast-core-engine"
version = "0.1.0"
edition = "2021"
authors = ["AST Copilot Helper Team"]
description = "High-performance Rust core engine for AST processing, vector operations, and batch file handling"
license = "MIT"
repository = "https://github.com/EvanDodds/ast-copilot-helper"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# NAPI-RS for Node.js bindings
napi = { version = "2.16", default-features = false, features = ["napi9", "serde-json", "tokio_rt"] }
napi-derive = { version = "2.16", features = ["type-def"] }

# Async runtime
tokio = { version = "1.35", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# High-performance data structures
dashmap = "6.1"
rayon = "1.8"

# Vector database and ML
candle-core = { version = "0.8", optional = true }
candle-nn = { version = "0.8", optional = true }
hnsw_rs = "0.3"

# Tree-sitter for AST parsing
tree-sitter = "0.24"
tree-sitter-typescript = "0.23"
tree-sitter-javascript = "0.23"
tree-sitter-python = "0.23"
tree-sitter-rust = "0.23"
tree-sitter-java = "0.23"
tree-sitter-cpp = "0.23"

# Database and storage
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite", "chrono", "uuid"] }
memmap2 = "0.9"

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Time and UUID
log = "0.4"
env_logger = "0.10"
uuid = { version = "1.10", features = ["v4", "serde"] }

# System information
sysinfo = "0.32"
num_cpus = "1.16"
chrono = { version = "0.4", features = ["serde"] }

# Test dependencies
tempfile = "3.12"
futures = "0.3"
fastrand = "2.0"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2"

[build-dependencies]
napi-build = "2.1"

[features]
default = ["embedding-models"]
embedding-models = ["candle-core", "candle-nn"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.release-with-debug]
inherits = "release"
debug = true
strip = false