[package]
name = "ast-core-engine"
version = "0.1.0"
edition = "2021"
authors = ["AST Copilot Helper Team"]
description = "High-performance Rust core engine for AST processing, vector operations, and batch file handling"
license = "MIT"
repository = "https://github.com/EvanDodds/ast-copilot-helper"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# NAPI-RS for Node.js bindings
napi = { version = "2.16", default-features = false, features = ["napi9", "serde-json", "tokio_rt"], optional = true }
napi-derive = { version = "2.16", features = ["type-def"], optional = true }

# WASM-specific dependencies (optional)
wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
js-sys = { version = "0.3", optional = true }
serde-wasm-bindgen = { version = "0.6", optional = true }
getrandom = { version = "0.2", features = ["js"], optional = true }

# Async runtime (conditional features for WASM compatibility)
tokio = { version = "1.35", features = ["rt", "rt-multi-thread", "macros"], optional = true }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# High-performance data structures
dashmap = { version = "6.1", optional = true }
rayon = { version = "1.8", optional = true }

# Vector database and ML
candle-core = { version = "0.8", optional = true }
candle-nn = { version = "0.8", optional = true }
hnsw_rs = "0.3"

# Tree-sitter for AST parsing
tree-sitter = "0.24"
tree-sitter-typescript = "0.23"
tree-sitter-javascript = "0.23"
tree-sitter-python = "0.23"
tree-sitter-rust = "0.23"
tree-sitter-java = "0.23"
tree-sitter-cpp = "0.23"

# Database and storage (NAPI only)
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite", "chrono", "uuid"], optional = true }
memmap2 = { version = "0.9", optional = true }

# Logging and tracing (NAPI only)
tracing = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"], optional = true }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Time and UUID
log = "0.4"
env_logger = "0.10"
uuid = { version = "1.10", features = ["v4", "serde"] }

# System information
sysinfo = "0.32"
num_cpus = "1.16"
chrono = { version = "0.4", features = ["serde"] }

# Test dependencies
tempfile = "3.12"
futures = "0.3"
fastrand = "2.0"

[dev-dependencies]
wasm-bindgen-test = "0.3"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2"

[build-dependencies]
napi-build = "2.1"

[features]
default = ["napi-backend", "full-deps"]
napi-backend = ["napi", "napi-derive"]
full-deps = ["tokio", "sqlx", "memmap2", "tracing", "tracing-subscriber", "dashmap", "rayon"]
wasm-full = ["wasm", "dashmap", "rayon"]
ml = ["candle-core", "candle-nn"] 
# WASM feature excludes tokio, sqlx and other heavy dependencies incompatible with WASM
wasm = ["wasm-bindgen", "wasm-bindgen-futures", "js-sys", "serde-wasm-bindgen", "getrandom", "dashmap"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.release-with-debug]
inherits = "release"
debug = true
strip = false