[package]
name = "ast-helper-core-engine"
version = "0.1.0"
edition = "2021"
authors = ["AST Copilot Helper Team"]
description = "High-performance WASM core engine for vector operations and AST processing"
license = "MIT"
repository = "https://github.com/EvanDodds/ast-copilot-helper"

[lib]
crate-type = ["lib", "cdylib"]

[[bin]]
name = "ast-parser"
path = "src/bin/ast_parser.rs"
required-features = ["full-system"]

[dependencies]
# WASM-specific dependencies
wasm-bindgen = { version = "0.2" }
wasm-bindgen-futures = { version = "0.4" }
js-sys = { version = "0.3" }
serde-wasm-bindgen = { version = "0.6" }
getrandom = { version = "0.2", features = ["js"] }
uuid = { version = "1.10", features = ["v4", "serde", "js"], default-features = false }

# Async runtime - features depend on target
tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread", "sync", "time"], default-features = false }

# Database and storage (WASM-compatible)
sqlx = { version = "0.8", features = ["sqlite", "chrono", "uuid"], default-features = false, optional = true }

# Concurrent data structures and sync
dashmap = "6.1"

# System utilities (WASM-compatible)
sysinfo = { version = "0.32", optional = true }
num_cpus = { version = "1.16", optional = true }

# Platform-specific dependencies
libc = { version = "0.2", optional = true }

# AST parsing
tree-sitter = { version = "0.20", optional = true }

# Tree-sitter language parsers
tree-sitter-javascript = { version = "0.20", optional = true }
tree-sitter-python = { version = "0.20", optional = true }
tree-sitter-typescript = { version = "0.20", optional = true }
tree-sitter-c = { version = "0.20", optional = true }
tree-sitter-java = { version = "0.20", optional = true }
tree-sitter-cpp = { version = "0.20", optional = true }
tree-sitter-c-sharp = { version = "0.20", optional = true }
tree-sitter-rust = { version = "0.20", optional = true }
tree-sitter-go = { version = "0.20", optional = true }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Futures
futures = "0.3"

# Random utilities
fastrand = "2.0"

# CLI dependencies
clap = { version = "4.0", features = ["derive"], optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"
tokio = { version = "1.0", features = ["full"] }
tempfile = "3.0"

[features]
default = ["full-system"]
wasm = [] # WASM build without system dependencies
full-system = ["sqlx", "sysinfo", "num_cpus", "tree-sitter", "tree-sitter-javascript", "tree-sitter-python", "tree-sitter-typescript", "tree-sitter-c", "tree-sitter-java", "tree-sitter-cpp", "tree-sitter-c-sharp", "tree-sitter-rust", "tree-sitter-go", "libc", "tokio/fs", "sqlx/runtime-tokio", "clap"] # Include system dependencies for native builds

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.release-with-debug]
inherits = "release"
debug = true
strip = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O", "--enable-bulk-memory", "--enable-nontrapping-float-to-int"]