/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 * Global TypeScript declarations for WASM modules generated by wasm-pack
 * This allows TypeScript to understand dynamic imports of WASM modules
 */

// WASM module for ast_helper_core_engine
declare module "*/wasm-pkg/ast_helper_core_engine.js" {
  export function init_vector_database_wasm(config_js: any): string;
  export function add_vector_wasm(
    node_id: string,
    embedding: Float32Array,
    metadata_js: any,
  ): string;
  export function add_vectors_batch_wasm(vectors_js: any): string;
  export function search_vectors_wasm(
    query_vector: Float32Array,
    k: number,
    ef: number,
  ): string;
  export function update_vector_wasm(
    node_id: string,
    embedding: Float32Array,
    metadata_js: any,
  ): string;
  export function delete_vector_wasm(node_id: string): string;
  export function get_stats_wasm(): string;
  export function shutdown_wasm(): string;

  // Default export for WASM initialization
  const wasmInit: () => Promise<void>;
  export default wasmInit;
}

// Alternative declaration for different import patterns
declare module "*/wasm-pkg/ast_helper_core_engine" {
  export * from "*/wasm-pkg/ast_helper_core_engine.js";
  export { default } from "*/wasm-pkg/ast_helper_core_engine.js";
}

// Specific relative path declaration
declare module "./database/vector/wasm-pkg/ast_helper_core_engine.js" {
  export * from "*/wasm-pkg/ast_helper_core_engine.js";
}

declare module "./database/vector/wasm-pkg/ast_helper_core_engine" {
  export * from "*/wasm-pkg/ast_helper_core_engine.js";
}
