name: ast-copilot-helper
version: '1.0.0'
summary: Advanced AST-powered development assistant
description: |
  AST Copilot Helper is a powerful command-line tool that provides advanced
  Abstract Syntax Tree (AST) analysis and intelligent code insights for multiple
  programming languages. It helps developers understand code structure, identify
  patterns, and improve code quality through sophisticated static analysis.

  Key Features:
  * Multi-language Support: Supports 15+ programming languages including
    JavaScript, TypeScript, Python, Go, Rust, and more
  * AST Analysis: Deep structural code analysis using native parsers  
  * Intelligent Insights: AI-powered code suggestions and improvements
  * VS Code Integration: Seamless integration with Visual Studio Code
  * Performance Optimized: Built with Rust for maximum performance
  * Cross-platform: Works on Windows, macOS, and Linux

grade: stable
confinement: strict
base: core22

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  ast-copilot-helper:
    command: bin/ast-copilot-helper
    plugs:
      - home
      - removable-media
      - network
      - network-bind

parts:
  ast-copilot-helper:
    plugin: dump
    source: .
    organize:
      ast-copilot-helper: bin/ast-copilot-helper
    stage:
      - bin/ast-copilot-helper
    prime:
      - bin/ast-copilot-helper