name: Quick Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review] # Only ready-for-review PRs
    paths:
      - "**.ts"
      - "**.js"
      - "**.json"
      - "packages/**"
      - ".github/workflows/**"

jobs:
  quick-check:
    name: Quick Check
    runs-on: ubuntu-latest
    # Skip draft PRs - only run on ready-for-review PRs
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Type check
        run: npm run type-check

      - name: Lint
        run: npm run lint

      - name: Quick tests
        run: npm run test:quick
        timeout-minutes: 5
